Feat/36 update de imagem
ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e2-proj-int-t8-e2-grp1-langsocials pull request #42
Opened 2023-05-25 13:00 UTC by Rafael-Pedro

2023-05-25 23:52 UTC, Vasconcelos-Carlos approved these changes

2023-05-26 00:05 UTC, Adeilton-Ro requested changes

2023-05-26 00:05 UTC, Adeilton-Ro commented on src/Presentation/Server/Controllers/AccountController.cs
> +        [HttpPut()]
colocar rota no parâmetro do httpput

2023-05-26 00:18 UTC, Adeilton-Ro approved these changes

2023-05-26 00:20 UTC, merged